version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - php
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    environment:
      TZ: "Asia/Tokyo"
    restart: unless-stopped
