version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - php
      - ruby
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./log/php/codeigniter:/var/www/html/php/application/logs"
    restart: unless-stopped
  ruby:
    build:
      context: .
      dockerfile: ./containers/ruby/Dockerfile
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./log/ruby:/var/log/ruby"
    restart: unless-stopped
